# Generated by Django 5.1.2 on 2024-10-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
